#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

#Depending on the operating system of the host machines(s) that will build or run the containers, the image specified in the FROM statement may need to be changed.
#For more information, please see https://aka.ms/containercompat

# syntax=docker/dockerfile:1
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["ImmedisWeb/ImmedisWeb.csproj", "ImmedisWeb/"]
RUN dotnet restore "ImmedisWeb/ImmedisWeb.csproj"

# Copy everything else and build
COPY . .
WORKDIR "/src/ImmedisWeb"
RUN dotnet build "ImmedisWeb.csproj" -c Release -o /app/build

# Build runtime image
FROM build AS publish
RUN dotnet publish "ImmedisWeb.csproj" -c Release -o /app/publish

FROM build-env AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ImmedisWeb.dll"]